---
inherit_from: .rubocop_todo.yml

require:
  - rubocop-rails
  - rubocop-minitest
  - rubocop-performance

AllCops:
  NewCops: enable

Naming/InclusiveLanguage:
  Exclude:
    - config/environments/development.rb # Bullet uses whitelist :(

# Not gonna rewrite all our tests...
Minitest/MultipleAssertions:
  Enabled: false

Rails/ActionControllerTestCase:
  Enabled: false


...
