name: 'Reusable: Build and push image'

on:
  workflow_call:
    inputs:
      environment:
        description: "Environment to run in"
        type: string
        required: true
      project_name:
        description: "Project name, e.g. pitc-ptime-int"
        type: string
        required: true
      push:
        description: "Build and debug things without pushing to the registry"
        type: boolean
        default: false

    secrets:
      PUZZLE_REGISTRY:
        description: 'FQDN of the registry'
        required: true
      PUZZLE_REGISTRY_USERNAME:
        description: 'Needed for the registry login'
        required: true
      PUZZLE_REGISTRY_TOKEN:
        description: 'Needed for the registry login'
        required: true

jobs:
  build:
    environment: ${{ inputs.environment }}
    runs-on: 'ubuntu-latest'
    steps:
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ${{ secrets.PUZZLE_REGISTRY }}
          username: ${{ secrets.PUZZLE_REGISTRY_USERNAME }}
          password: ${{ secrets.PUZZLE_REGISTRY_TOKEN }}

      - uses: docker/build-push-action@v4
        with:
          file: Dockerfile
          build-args: |
            BUILD_REPO=$GITHUB_REPOSITORY
            BUILD_REF=$GITHUB_REF_NAME
            BUILD_COMMIT=$GITHUB_SHA
          target: app
          tags: |
            ${{ secrets.PUZZLE_REGISTRY }}/ptime/${{ inputs.project_name }}/rails:latest
            ${{ secrets.PUZZLE_REGISTRY }}/ptime/${{ inputs.project_name }}/rails:${{ github.sha }}
          push: ${{ inputs.push }}
