name: 'Code Style Review'

on:
  workflow_call:

jobs:
  lint:
    runs-on: 'ubuntu-latest'

    steps:
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - uses: reviewdog/action-rubocop@v2
        with:
          rubocop_version: gemfile
          rubocop_extensions: rubocop-minitest:gemfile rubocop-performance:gemfile rubocop-rails:gemfile
          # reporter: github-pr-review
          level: error

      - run: 'gem install haml-lint'

      - uses: reviewdog/action-setup@v1

      - name: 'Run Reviewdog HAML-Lint'
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ github.token }}
        run: |
          haml-lint |
          reviewdog \
          -efm="%f:%l %m" \
          -name="HAML-Lint" \
          -reporter=github-pr-review \
          -level=error \
          -diff="git diff $DIFF_BRANCH"
