name: 'Lint and test on pull request'

on:
  pull_request_target:
    branches:
      - 'master'
    paths-ignore:
      - 'doc/**'
      - '**.md'

jobs:
  lint:
    uses: ./.github/workflows/reusable-lint.yaml
    with:
      ref: ${{ github.ref_name }}

  test:
    uses: ./.github/workflows/reusable-test.yaml
    with:
      ref: ${{ github.ref_name }}

